[workspace]
members = [
    "stubot-chess",
    "stubot-engine",
    "stubot-perftree",
    "stubot-uci",
    "stubot-wasm"
]
default-members = [
    "stubot-chess",
    "stubot-engine",
    "stubot-uci"
]

[profile.release]
lto = true
opt-level = "s"