[workspace]
members = [
    "stubot-chess",
    "stubot-engine",
    "stubot-perftree",
    "stubot-uci"
]
default-members = [
    "stubot-chess",
    "stubot-engine",
    "stubot-uci"
]

[profile.release]
debug = true
